### ISSUE TITLE
Name generator broken

### ISSUE THREAD

**Issue by Titstewan** [Titstewan/Tirea-Material-Lesson-Blog#1]
Well, it's not really broken, but if one try to choose custom variable, it won't work, everything else works fine.

**Comment by Titstewan** [comment]
Addendum:
The link has to look like: **?page=generator&a=X&b=X&c=X**
(X = number)

**Comment by tirea** [comment]
It just needs to be its own independent file. Because it requests vars from itself. Trying to have index.php handle this thing causes the vars from the form to be posted to index.php instead of back to itself. And you had made it so generate.php allows no direct access.

Fixed this bug by separating it out.

**Comment by Titstewan** [comment]
Or a different $_REQUEST method as mentioned here https://github.com/Titstewan/Tirea-Material-Lesson-Blog/issues/3#issuecomment-277755111

**Comment by tirea** [comment]
Name Generator now completely working as index.php?page=generator (URL vars a=, b=, c=, k=, hrh= all work. Form submission also works.)

O, teh HAX I pulled to get this to work = HRH.gif

There HAS to be a better way than the epic hack I used to get this to work. 

Even if it's terrible ugly code, it functions flawlessly for the end-user.

**Comment by Titstewan** [comment]
I just returned back from work. Excellent work, ma Tirea, :D I had the same idea to write that. I would not call this an epic hack because SMF for example does it quite similar. :P

**Comment by tirea** [comment]
Even with a display:none text input field? HRH!

**Comment by Titstewan** [comment]
LOLcano!
