### ISSUE TITLE
An empty line...

### ISSUE THREAD

**Issue by Titstewan** [Titstewan/Tirea-Material-Lesson-Blog#11]
An empty line prevents cookie to be sent...
![bug](https://cloud.githubusercontent.com/assets/12980504/24215721/e5329364-0f39-11e7-8b95-918f14120ed2.png)

**Comment by tirea** [comment]
That makes less than no sense. How could an empty line in a file prevent PHP from writing data to a cookie or prevent the browser from supplying its value to PHP? O__0

**Comment by Titstewan** [comment]
Empty line fixed...
But still, I cant set up a damn cookie.,,

**Comment by tirea** [comment]
Got the cookie to work. :)
