### ISSUE TITLE
auto rss feed

### ISSUE THREAD

**Issue by Titstewan** [Titstewan/Tirea-Material-Lesson-Blog#16]
automated rss feed, i think.

**Comment by tirea** [comment]
Yes, it should be easy to automate. Can PHP even be used in an .xml file? o.o maybe, with edited server settings?

**Comment by Titstewan** [comment]
hmm, php can out put something as .xml

**Comment by tirea** [comment]
Work in progress has begun with this at the bottom of source.php

**Comment by tirea** [comment]
International Automatic RSS Feed is now operational.

index.php?p=rss&lang=english
index.php?p=rss&lang=german
index.php?p=rss&lang=dutch
index.php?p=rss&lang=czech
index.php?p=rss&lang=french
index.php?p=rss&lang=navi
