### ISSUE TITLE
Lesson pages

### ISSUE THREAD

**Issue by Titstewan** [Titstewan/Tirea-Material-Lesson-Blog#3]
I want to find an elegant way to let include the lessons...

**Comment by tirea** [comment]
Have an idea for this. Will clone this repo after work.

**Comment by tirea** [comment]
To sort of explain what I meant in my tweet
( https://twitter.com/TireaAean/status/828575895027851265 )

It would be easiest and best for me to have lesson content still be separate files inside a directory like /lessons. I also want to start writing my lesson content in markdown because it's faster and easier to write and read than html. I've found a good markdown → html parser written in PHP that we can clone into our project and include in source.php.

The plan is, (hope this works) have a new function in source.php that: 
* request $l (filename without extension)
* find /lessons/$l.md
* Parse that markdown file and echo it as HTML

So, if index.php?page=lesson&l=01 then:
* request given .md filename (01 here)
* pass it to source.php somehow
* call the new function so that the selected lesson is loaded

**Comment by Titstewan** [comment]
A php function that parse the lessons need to be written in the source.php or in an own file.
The thing I bang on is that _index.php?page=lessons_**&l=01**, A similar solution is/was required for the name generator _index.php?page=generator_**&a=#&b=#&c=#**, btw. I'll read some php sources/documentations.

**Comment by tirea** [comment]
The easiest way to do this is make l global and accessible to source.php even if it was first requested and set by index. Only way I can think of that would theoretically work.

**Comment by Titstewan** [comment]
I would *not* make the source.php accessible, because ... yeah, it will really look broken, hrh. Also, the idea why I didn't make it accessible is to increase the website security.
I'll try to find a good solution for this because this is currently the only thing that break pages.
Kop, a solution for this would make it possible to extend the page like Kemaweyan's number converter http://forum.learnnavi.org/index.php?msg=595316.0 or other cool stuff that uses buttons and stuff.

**Comment by tirea** [comment]
What I meant is, inside index.php, have declared global variable $l
This way, source.php can use that variable when it goes to run the parse+echo function.
Either that, or we need a different structure to the entirely for how index.php calls source.php.

Wait a second. Can index.php not just call a function with a parameter in it?

"lessons" => ... "source.php", "navi_lesson(".$_request['l'].")"

Or something?
The index can pass the requested lesson number straight into a source.php function like this kefyak?

**Comment by Titstewan** [comment]
I think, the thing is this:
```php
	require_once($sourcedir . '/' . $pageArray[$_REQUEST['page']][0]);
	return $pageArray[$_REQUEST['page']][1];
```
It calls everything that is in the $pageArray, everything else go bye bye.
Methinks, one would write a small function that parse page specific requests differently without using superglobals.

**Comment by tirea** [comment]
Markdown lessons completely supported now.

**Comment by Titstewan** [comment]
Oer_sunu.png

**Comment by Titstewan** [comment]
Yes, I've improved a very few things and added two test lessons and yup the parser works nice!
We need a function for $lnum that read the file names in the lesson directory.

**Comment by tirea** [comment]
On Feb 7, 2017 11:18, "Tìtstewan" <notifications@github.com> wrote:

Yes, I've improved a very few things and added two test lessons and yup the
parser works nice!

:D

We need a function for $lnum that read the file names in the lesson
directory.


Does it not already do this? If you click a link that has
href="index.php?page=lessons&l=1" for example... It should already try to
parse and display 'lessons/'.$_REQUEST['l'].'.md'

O_0

**Comment by Titstewan** [comment]
I see what you wrote there, hrh, sran ulte mllte.
I still HRH nìhawng about that hax :P :P :P

**Comment by tirea** [comment]
Told you it was teh hax. XD

Also, see source.php latest commit (2 min ago)

**Comment by Titstewan** [comment]
https://github.com/Titstewan/Tirea-Material-Lesson-Blog/blob/master/source.php#L644
(PHP chat incomming HRH.gif)
