### ISSUE TITLE
Adding a dictionary generator page?

### ISSUE THREAD

**Issue by Titstewan** [Titstewan/Tirea-Material-Lesson-Blog#4]
Adding / not adding?
https://github.com/Titstewan/DictionaryGenerator

**Comment by tirea** [comment]
If that's the one from LN /navi-vocabulary then nah let's keep it just
there. :)

**Comment by Titstewan** [comment]
Yeah, unlike the dictinary page on /navi-vocablary this one have not to be manually updated time to time. :P
