### ISSUE TITLE
Invalid cookie value causes HTTP Error 500

### ISSUE THREAD

**Issue by tirea** [Titstewan/Tirea-Material-Lesson-Blog#40]
Steps to reproduce:

1. [Use an invalid language choice in the URL](http://tirea.learnnavi.org/test/index.php?lang=derp)
2. See blank page or Error 500

To fix the 500, until cookie value and URL var are validated:

1. Use a legitimate value of a language that is actually supported, such as: [this](http://tirea.learnnavi.org/test/index.php?lang=english)
2. Page now loads as expected, using English.

I recommend the following to fix this bug:

Force the setting of only acceptable values to the cookie. This way, the value can never be invalid no matter how hard user tries. Also, because of this, we would not need to check validity of the var in every single file of function where it's used.

**Comment by Titstewan** [comment]
Oy...
One could write a small check if the cookie value is in array(language) load the <language> else default language or something.

**Comment by tirea** [comment]
I recommend in index.php another function very similar to hp_main()

- index.php hp_main() validates p quite well.
- source.php navi_lesson() is written in a way that already validates l quite well.
- generate.php valid() validates a,b,c,k well but probably needs to ensure they are ints.

All validations need a default case if it turns out user did something invalid:

- hp_main() already does expected default behavior of header Location index.php when p is invalid.
- navi_lesson() already does expected default behavior of load the lesson index when l is invalid.
- valid() I'm not sure but just generates one name where a,b,c,k = 1,1,1,1

Now we need to have a check and default behavior when $_COOKIE['lang'] or when $_GET['lang'] are invalid.

**Comment by Titstewan** [comment]
I've added some codes, even if I am in zombie-mode, hrh.
Please, test it, also try to use some hax0rzz to check if stuff is secure and don't break.

**Comment by tirea** [comment]
I've tried all the hax I can think of on every possible URL var or Form element. It's solid and all works as it should

Nice work :)
