### ISSUE TITLE
Automate the cookie validation and lang menu

### ISSUE THREAD

**Issue by Titstewan** [Titstewan/Tirea-Material-Lesson-Blog#41]
if we can automate the cookie verification AND the lang menu, one only need to add a new lesson and stuff will do the work without editing the php files.

**Comment by tirea** [comment]
I do believe that I have successfully automated the Language Menu :'D

**Comment by tirea** [comment]
AAAAnd Cookie Validation is now automated too. :D :D

GOOD EVENING, RC1!!

**Comment by Titstewan** [comment]
No, good evening first final version! :D
