### ISSUE TITLE
Language Switcher Broken Due To 2 Cookies

### ISSUE THREAD

**Issue by tirea** [Titstewan/Tirea-Material-Lesson-Blog#45]
This bug exists on both Firefox and Chrome.

Steps to reproduce:
1. Clear all cookies in the browser
2. Visit the [Test Site](http://tirea.learnnavi.org/test/index.php)
3. Check Cookies in Firebug. You will see one cookie already, default set by index.php:
```
lang        english        .tirea.learnnavi.org  11 B        /  <expire date> 
```
notice the dot before $domain (HOW TF does that get there?)

4. Switch language to any language using the language menu (Esperanto, z.B.)
5. Check the Cookies in Firebug again. Now there are two:
```
lang        esperanto   tirea.learnnavi.org  11 B         /  <expire date> 
lang        english        .tirea.learnnavi.org  11 B        /  <expire date> 
```
6. Switch language again to something else and check cookies again:
```
lang        german       tirea.learnnavi.org  11 B         /  <expire date> 
lang        english        .tirea.learnnavi.org  11 B        /  <expire date>
```

Result: Language Switcher does not work. Stays in English the entire time.

Hack-fix: 

1. Use [http://tirea.learnnavi.org/test/index.php?lang=esperanto]([http://tirea.learnnavi.org/test/index.php?lang=esperanto) z.B. to actually have target language load.
2. Checking cookies again, we see (if just now following these steps right after step 6 above):
```
lang        esperanto      .tirea.learnnavi.org  11 B         /  <expire date> 
lang        german           tirea.learnnavi.org  11 B        /  <expire date>
```
3. Switch language again using URL: `index.php?lang=dutch` z.B.
4. Check again:
```
lang        dutch        .tirea.learnnavi.org  11 B        /  <expire date>
lang        german     tirea.learnnavi.org  11 B         /  <expire date> 
```

Interesting indeed. What on Pandora is causing this? the Flux Vortex? This wasn't happening before...
I have checked and All functions in our PHP that calls setcookie() use $domain var from settings.php which on the server is set `$domain = 'tirea.learnnavi.org';` (with no dot at beginning)

I have no idea how this is happening or how to fix this. O__o

**Comment by tirea** [comment]
Note: This does not happen on Localhost, but it happens on Test Site actual.

Note that the ?lang= hack fix does work but it should definitely not be the only way to get the language to switch. In fact, the language menu should work and ?lang= should not even be really known to people. meh.

**Comment by Titstewan** [comment]
What kind of sorcercy is this?
Since when is this? Methinks, it could be something during the cookie validation?, Meh, why it can't be weekend now.

**Comment by tirea** [comment]
And the day is saved. Test Site language switcher now works.

Turns out specifying domain in setcookie() causes this weirdness. I removed every instance of $domain everywhere. Browser auto assumes domain from calling hostname, no more leading dot sourcery, all is win.
