### ISSUE TITLE
Language specific links doesn't work

### ISSUE THREAD

**Issue by Titstewan** [Titstewan/Tirea-Material-Lesson-Blog#47]
Clicking on a link that contain l=01g-german for example loads only stuff that was stored in the cookie like english or any other language.
A possible fix ould be to let update the cookie lang value also by requesting a specific language lesson.

**Comment by tirea** [comment]
I thought about this solution too. I think it's a pretty good way to go. Set $lang equal to the end of $l if it's set. And forcing the cookie to update by requesting a lesson file written in that language.

Are you already on this fix?

**Comment by Titstewan** [comment]
I'll be on it when I am back at from work. (10 hours)

**Comment by tirea** [comment]
Txantsan! irayo :)

**Comment by Titstewan** [comment]
Bug fix committed. :D
