### ISSUE TITLE
Internationalize stuff

### ISSUE THREAD

**Issue by Titstewan** [Titstewan/Tirea-Material-Lesson-Blog#6]
I'll try this evening to lurk to add some code to make this blog international by integrating some kind of text strings.

**Comment by Titstewan** [comment]
A switching function we need!

**Comment by tirea** [comment]
I've got it all done now. 

FOR THE WIN.

Now all we need is a lessons/01g-german.md so that it doesn't vomit a "File Not found" error ;)

**Comment by vawm** [comment]
Esperanto ftw

**Comment by tirea** [comment]
lessons/01c-english.md ;)

okay, so the language switcher and auto-loading of correct file works with one pretty major exception

BUG: Currently, switching language while already reading a lesson will only switch the language of the interface. It will NOT switch the file the user is reading.

**Comment by Titstewan** [comment]
I'll have a look on this...

**Comment by Titstewan** [comment]
That bug has been fixed, woo!
RC 1 is getting closer and closer :D

A few things need to be done, though.

**Comment by tirea** [comment]
What's left? O_0? German Translations?

**Comment by Titstewan** [comment]
minor code optimation.

**Comment by tirea** [comment]
Very interesting solution to the Switch Language While Reading Lesson bug.

Now, URL doesn't change, yet the content echoed does change in this situation.

One could have Esperanto text even when URL says http://localhost/material/index.php?p=lessons&l=01c-czech  HRH :D

**Comment by Titstewan** [comment]
Is this bad? Otherwise it's HRH :D I did not expect that.

**Comment by tirea** [comment]
The user experience works as it should. Probably no one will notice that HRH in the URL. :P I don't think it's a huge deal, but technically a small bug.

**Comment by tirea** [comment]
I've also fix0r'd the loop fail in source.php navi_lesson()

**Comment by vawm** [comment]
muh Esperanto propaganda :P

**Comment by Titstewan** [comment]
So, the main work on this is completed, particulary the backend development. With this, I'm going to close this. :)
